### ISSUE TITLE
SQL 실행 결과 이미지 수정

### ISSUE THREAD

**Issue by beyondswcamp** [beyond-sw-camp/be06-1st-Dopamines-BOOT_UP#9]
![스크린샷 2024-05-21 132913](https://github.com/beyond-sw-camp/be06-1st-Dopamines-BOOT_UP/assets/148842087/e80cfbd8-5460-42eb-8bbb-a5d5f6728ecf)

- [ ] 해당 이미지가 보이게 수정 요청 드립니다.

**Comment by 706com** [comment]
수정 완료 했습니다 ~
